steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['package']            
artifacts:
  mavenArtifacts:
  - repository: 'https://europe-west1-maven.pkg.dev/${PROJECT_ID}/becpg-mvn'
    path : '/workspace/becpg-artworks/becpg-artworks-share-docker/target/becpg-artworks-share-4.2.1.0.amp'
    artifact_id: 'becpg-artworks-share'
    group_id: 'fr.becpg.artworks'
    version: '4.2.1.0'
  - repository: 'https://europe-west1-maven.pkg.dev/${PROJECT_ID}/becpg-mvn'
    path : '/workspace/becpg-artworks/becpg-artworks-platform/target/becpg-artworks-platform-4.2.1.0.amp'
    artifact_id: 'becpg-artworks-platform'
    group_id: 'fr.becpg.artworks'
    version: '4.2.1.0'    